"""empty message

Revision ID: 2672489f8594
Revises: 2a7e1caaa34a
Create Date: 2022-05-03 11:31:33.094718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2672489f8594'
down_revision = '2a7e1caaa34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
