"""empty message

Revision ID: e3d77ae335b1
Revises: 2672489f8594
Create Date: 2022-05-03 12:40:32.178202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d77ae335b1'
down_revision = '2672489f8594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github', sa.String(length=5000), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'github')
    # ### end Alembic commands ###
